#version: '3.1'
#services:
#  accounting-api:
#    container_name: accounting
#    image: ${GROUP_ID}/Accounting-Project-Api:${SERVICE_VERSION:-latest}
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      DATABASE_HOST: database
#      DATABASE_PORT: 5432
#      DATABASE_NAME: accounting-api
#      DATABASE_USERNAME: postgres
#      DATABASE_PASSWORD: admin
#      DATABASE_SSL: 'false'
#      SLEEP_LENGTH: 5
#    ports:
#      - "8002:8002"
#    depends_on:
#      - database
#      -
#  database:
#    image: postgres
#    container_name: database
#    networks:
#      - backend
#    ports:
#      - "5432:5432"
#    volumes:
#      - .m2:/root/.m2
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: accounting-api
#
#  keycloak:
#    container_name: keycloak_blog
#    image: "quay.io/keycloak/keycloak:22.0.3"
#    volumes:
#      - ./keycloak-data:/opt/keycloak/data/h2
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    ports:
#      - "8080:8080"
#    networks:
#      - backend
#
#networks:
#  backend:
#    driver: bridge
#
#
#volumes:
#  database:


