
#  accounting-api:
#    container_name: accounting
#    image: ${GROUP_ID}/Accounting-Project-Api:${SERVICE_VERSION:-latest}
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      DATABASE_HOST: database
#      DATABASE_PORT: 5432
#      DATABASE_NAME: accounting-api
#      DATABASE_USERNAME: postgres
#      DATABASE_PASSWORD: admin
#      DATABASE_SSL: 'false'
#      SLEEP_LENGTH: 5
#    ports:
#      - "8002:8002"
#    depends_on:
#      - database
#      -




services:
  keycloak:
    container_name: keycloak_22
    image: "quay.io/keycloak/keycloak:22.0.3"
    volumes:
      - /Users/zouliga/Documents/data/keycloak:/opt/keycloak/data/h2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - backend


  pgdb:
    container_name: pgdb
    image: "postgres:latest"
    volumes:
      - /Users/zouliga/Documents/data/pgdata:/var/lib/mysql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  keycloak:
  pgdata:

networks:
  backend:
    driver: bridge