
### Login as Root User
POST http://localhost:8080/realms/zouliga-dev/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = Accounting-Project-Api &
username = admin@greentech.com &
password = Abc1 &
client_secret = wV5ySbtiw7E2DppfgmMdK16adcEndRCy

> {%
    client.global.set("auth-token", response.body.access_token);
%}


### List all Users
GET http://localhost:8081/api/v1/users/list
Accept: application/json
Authorization: Bearer {{auth-token}}



### Create User
POST http://localhost:8081/api/v1/users/create
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth-token}}

{
  "username": "user@email.com",
  "password": "Abc1",
  "firstname": "Latif",
  "lastname": "Zouliga",
  "phone": "1-222-333-4444",
  "enabled": true,
  "role": {
    "id": 2
  },
  "company": {
    "id": 2
  },
  "onlyAdmin": true
}

> {%
    client.global.set("username", response.body.data.username)
%}




### Update User
PATCH http://localhost:8081/api/v1/users/update/{{username}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth-token}}

{
  "firstname": "Abdellatif",
  "lastname": "zagalo"
}


### Delete User
DELETE http://localhost:8081/api/v1/users/delete/{{username}}
Authorization: Bearer {{auth-token}}
